// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dt191g_moment4.Data;

#nullable disable

namespace dt191g_moment4.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20250225145007_SeedMusicData")]
    partial class SeedMusicData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("dt191g_moment4.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasAnnotation("Relational:JsonPropertyName", "album");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Divide"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Back in Black"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Abbey Road"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Future Nostalgia"
                        });
                });

            modelBuilder.Entity("dt191g_moment4.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Artist = "Ed Sheeran",
                            Category = "Pop",
                            Length = 233,
                            Title = "Shape of You"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            Artist = "Ed Sheeran",
                            Category = "Pop",
                            Length = 263,
                            Title = "Perfect"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 2,
                            Artist = "Michael Jackson",
                            Category = "Pop",
                            Length = 294,
                            Title = "Billie Jean"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 2,
                            Artist = "Michael Jackson",
                            Category = "Pop",
                            Length = 358,
                            Title = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 3,
                            Artist = "AC/DC",
                            Category = "Rock",
                            Length = 255,
                            Title = "Back in Black"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 3,
                            Artist = "AC/DC",
                            Category = "Rock",
                            Length = 210,
                            Title = "You Shook Me All Night Long"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 4,
                            Artist = "The Beatles",
                            Category = "Rock",
                            Length = 259,
                            Title = "Come Together"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 4,
                            Artist = "The Beatles",
                            Category = "Rock",
                            Length = 185,
                            Title = "Here Comes the Sun"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 5,
                            Artist = "Dua Lipa",
                            Category = "Pop",
                            Length = 183,
                            Title = "Don't Start Now"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 5,
                            Artist = "Dua Lipa",
                            Category = "Pop",
                            Length = 203,
                            Title = "Levitating"
                        },
                        new
                        {
                            Id = 11,
                            Artist = "Adele",
                            Category = "Pop",
                            Length = 295,
                            Title = "Hello"
                        });
                });

            modelBuilder.Entity("dt191g_moment4.Models.Song", b =>
                {
                    b.HasOne("dt191g_moment4.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("dt191g_moment4.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
